### ISSUE TITLE
MAC address is already randomized in Qubes 4.1

### ISSUE THREAD

**Issue by deeplow** [kennethrrosen/qubes-for-journalists#1]
The MAC address is already randomized in Qubes 4.1 (see [here](https://forum.qubes-os.org/t/change-mac-address-and-hostname-by-default/13182/18)). So the rather large section ["anonymize MAC address and hostname"](https://github.com/kennethrrosen/journoQUBES/#anonymize-mac-address-and-hostname) is not needed.

**Comment by kennethrrosen** [comment]
Thanks for flagging. Will maintain the Hostname randomize file and remove the MAC address section.
